spring.application.name=discovery-client-service

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.hostname=localhost

# Giả lập Lỗi 8: Chế độ Tự Bảo Vệ của Eureka (Eureka Self-Preservation)
# Để mô phỏng: Hãy bỏ comment cấu hình dưới đây để Eureka giữ lại instance chết mà không đuổi (evict) đi.
# eureka.server.enable-self-preservation=true
# eureka.server.eviction-interval-timer-in-ms=3000

management.endpoint.health.enabled=true
management.endpoints.web.exposure.include=*

# Server
server.port=8761
